name: chiefcommander
favicon: null
layout_spectrum: 0.7039418118074536
typography_spectrum: 0.9396382614504546
title: 'CHIEF COMMANDER '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8348993309773505
  lightness: 0.22863416047766805
  saturation: 0.292226315010339
  rhythmicContrast: 0.8087868557777256
purpose: []
