name: chiefcommander
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39944
title: 'CHIEF COMMANDER '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#faf8ec'
    - '#775c2e'
    - '#9d954c'
    - '#d7c868'
  brandStrength: 0.5625
  lightness: 0.25
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
